# Generated by Django 5.2.7 on 2025-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemcategory_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
