# Generated by Django 5.2.7 on 2025-12-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pack_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of individual units per pack'),
        ),
    ]
