# Generated by Django 5.2.7 on 2025-12-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_pack_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='pack_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
