"""
Django settings for printsys project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS","127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'inventory.apps.InventoryConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'printsys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'printsys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
from urllib.parse import urlparse
DATABASE_URL = os.getenv('DATABASE_URL', None)

if DATABASE_URL:
    db_url = urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",  # Assuming PostgreSQL
            "NAME": db_url.path[1:],  # The first character is a '/', so we skip it
            "USER": db_url.username,
            "PASSWORD": db_url.password,
            "HOST": db_url.hostname,
            "PORT": db_url.port,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.{}'.format(
                os.getenv('DATABASE_ENGINE', 'sqlite3')
            ),
            'NAME': os.getenv('DATABASE_NAME', 'postgres'),
            'USER': os.getenv('DATABASE_USERNAME', 'dbuser'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', 'dbpassword'),
            'HOST': os.getenv('DATABASE_HOST', '127.0.0.1'),
            'PORT': os.getenv('DATABASE_PORT', 5432),
        }
    }  


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'printsys/static'),
#]

MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, 'media'))  
MEDIA_URL = os.getenv("MEDIA_PATH", "/media/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'

APP_NAME = "Printsys"

UNFOLD = {
    "SITE_TITLE": "BJ Lajara Printing Press",
    "SITE_HEADER": APP_NAME,
    "SITE_URL": "/",
    "SITE_SYMBOL": "graph_5",  # symbol from icon set
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "command_search": False,  # Replace the sidebar search with the command search
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": "Navigation",
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        #"permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": reverse_lazy("admin:core_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Inventory",
                        "icon": "inventory",
                        "link": reverse_lazy("admin:inventory_item_changelist"),
                        "permission": lambda request: request.user.is_active,
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "page": "dashboard",
            "items": [
                {
                    "title": "Inventory",
                    "link": "#inventory",
                },
                {
                    "title": "Quotation",
                    "link": "#quotation" #reverse_lazy("admin:core_user_changelist"),
                }
            ]
        },
        {
            "models": [
                "core.user", "core.role"
            ],
            "items": [
                {
                    "title": "Users",
                    "link": reverse_lazy("admin:core_user_changelist"),
                    "permission": lambda request: request.user.is_superuser,
                },
                {
                    "title": "Roles",
                    "link": reverse_lazy("admin:core_role_changelist"),
                    "permission": lambda request: request.user.is_superuser,
                },
            ],
        },
        {
            "models": [
                "inventory.item", "inventory.supplier", "inventory.itemcategory", "inventory.stockmovementpurpose"
            ],
            "items": [
                {
                    "title": "Items",
                    "link": reverse_lazy("admin:inventory_item_changelist"),
                    "permission": lambda request: request.user.has_module_perms('inventory'),
                },
                {
                    "title": "Suppliers",
                    "link": reverse_lazy("admin:inventory_supplier_changelist"),
                    "permission": lambda request: request.user.has_module_perms('inventory'),
                },
                {
                    "title": "Item Categories",
                    "link": reverse_lazy("admin:inventory_itemcategory_changelist"),
                    "permission": lambda request: request.user.is_superuser,
                },
                {
                    "title": "Stock Action Purpose",
                    "link": reverse_lazy("admin:inventory_stockmovementpurpose_changelist"),
                    "permission": lambda request: request.user.is_superuser,
                },
            ],
        },
    ],
    "DASHBOARD_CALLBACK": "core.views.dashboard_callback",
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGGING = {  
    "version": 1,  
    "disable_existing_loggers": False,  
    "handlers": {"console": {"class": "logging.StreamHandler"}},  
    "loggers": {"": {"handlers": ["console"], "level": "DEBUG"}},  
}

WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG